#!/bin/sh /etc/rc.common
START=95
STOP=0
USE_PROCD=1

start_service() {
	:
}

stop_service() {
	procd_set_param timeout 30
	config_load qmodem
	config_foreach _soft_reboot modem-device
}

_soft_reboot() {
	config_get soft_reboot $1 soft_reboot
	[ "$soft_reboot" != "1" ] && return 0
	echo 517 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio517/direction
	echo 0 > /sys/class/gpio/gpio517/value
	echo 1 > /sys/class/gpio/gpio517/value
}